# Site
repository: shusingh/portfolio-website
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shubham Singh
title: Software Development Engineer
email: kshubhsingh@gmail.com
website: www.github.com/shusingh/portfolio-website

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  shusingh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: shubham_is_lucky
linkedin_username: shusingh
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pp.png
about_content: |
  Hello, I'm Shubham Kumar Singh, an innovative Software Development Engineer with a comprehensive background in cloud technologies, geospatial data analysis, and data-driven software solutions. At Amazon, I excel in building scalable systems and applying AWS services to optimize operations. My academic pursuits at Indiana University Bloomington, paired with real-world experience at Eli Lilly and Company, have honed my expertise in data engineering and software development.

  I am proficient in: <mark>Cloud Computing Platforms</mark>, <mark>Java</mark>, <mark>Python</mark>, <mark>ArcGIS</mark>, and <mark>QGIS</mark>. Beyond my professional life, I am an avid traveler with a taste for global cuisines and a penchant for hiking, gaming, and culinary exploration.

content:

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Amazon
        sub_title: Software Development Engineer
        caption: August 2022 - Present
        quote: >
          Innovating at the heart of Amazon's cross-border shipment solutions, harnessing the power of AWS.
        description: >
          As a Software Development Engineer at Amazon, I contribute to the backend systems facilitating cross-border shipments. My role involves enhancing cloud infrastructure, streamlining data processing pipelines, and employing AWS services to maximize system reliability and efficiency.

      - layout: left
        title: Eli Lilly and Company
        sub_title: Data Engineering Co-op
        caption: Jan 2021 - Feb 2021
        quote: >
          Tackling complex data challenges in the biopharmaceutical field to advance cancer research.
        description: >
          Engaged in a cooperative education program at Eli Lilly, where I developed ML models for cancer cell gene identification and orchestrated an ETL pipeline, gaining hands-on experience with Apache Airflow and Docker.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: Cost-Optimization Analyzer
        technologies: AWS Cost Explorer API, Lambda, DynamoDB, QuickSight
        description: >
          Developed an application to analyze AWS spending and offer cost-saving recommendations through pattern identification and resource optimization.

      - layout: left
        title: Dynamic Content Delivery Network (CDN)
        technologies: AWS CloudFront, Lambda@Edge, S3, Route 53
        description: >
          Designed a CDN that adaptively serves content based on user's location and preferences, significantly optimizing user experience.

      - layout: left
        title: Serverless Data Processing Pipeline
        technologies: AWS Lambda, S3, DynamoDB, API Gateway, Kinesis
        description: >
          Engineered a serverless pipeline for real-time data processing, utilizing Lambda for efficient data transformations and streamlined storage.

      - layout: left
        title: Real-Time Analytics Dashboard
        technologies: AWS Kinesis, Lambda, QuickSight, DynamoDB
        description: >
          Implemented a real-time analytics dashboard to visualize data streams, enhancing decision-making with up-to-the-minute insights.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Indiana University Bloomington
        sub_title: Masters in Computational Science
        caption: 2021 - 2022
        quote: >
          A curriculum ingrained with computational prowess and data science acumen.
        description: >
          Gained a solid grounding in computational science, integrating data analysis, machine learning, and cloud platforms like AWS and GCP. Emphasized collaborative and project-based learning to solve real-world problems.

  - title: A Little More About Me
    layout: text
    content: >
      My curiosity extends beyond the technical sphere to diverse hobbies such as hiking to reconnect with nature, strategizing in gaming worlds, and experimenting with recipes in the kitchen.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
